bind \cg 'mvt; commandline -f repaint'
bind \eg 'mvt -c; commandline -f repaint'
bind \e\[1\;3D 'cd -; commandline -f repaint'
bind \e\[1\;3C 'mvt -c; commandline -f repaint'
bind \e- 'cd ..; commandline -f repaint'
